# Generated by Django 5.1.4 on 2025-01-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_updated_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(help_text='Enter otp number.', max_length=128, verbose_name='password'),
        ),
    ]
