# Generated by Django 5.1.4 on 2025-01-15 23:09

import backend.srvs.office.gate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Enter email.', max_length=255, unique=True, validators=[backend.srvs.office.gate.models.EmailValidator()], verbose_name='username'),
        ),
    ]
