# Generated by Django 5.1.4 on 2024-12-17 21:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color_id', models.IntegerField(choices=[(1, 'White'), (2, 'Black'), (3, 'Gray'), (4, 'Silver'), (5, 'Pencil Tip'), (6, 'Blue')], null=True)),
                ('gearbox_id', models.IntegerField(choices=[(1, 'Automatic'), (2, 'Ribbed')], null=True)),
                ('is_offroad', models.BooleanField(blank=True, null=True)),
                ('price', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(10000000000000)])),
                ('rent_type_id', models.IntegerField(choices=[(1, 'Hourly'), (2, 'Daily'), (3, 'Weekly'), (4, 'Monthly')], null=True)),
                ('rent', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10000), django.core.validators.MaxValueValidator(1000000000000)])),
                ('built_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1350), django.core.validators.MaxValueValidator(1403)])),
                ('kilometer', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000000)])),
            ],
        ),
    ]
