# Generated by Django 5.1.4 on 2024-12-17 22:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company_id', models.IntegerField(choices=[(1, 'Iran Khodro'), (2, 'Saipa'), (3, 'Benz'), (4, 'Bmw'), (5, 'Volvo'), (6, 'Reno'), (7, 'Audi'), (8, 'Mvm'), (9, 'Porsche'), (10, 'Toyota'), (11, 'Jack'), (12, 'Suzuki'), (13, 'Chevrolet'), (14, 'Lexus'), (15, 'Hyundai')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color_id', models.IntegerField(choices=[(1, 'White'), (2, 'Black'), (3, 'Gray'), (4, 'Silver'), (5, 'Pencil Tip'), (6, 'Blue')], null=True)),
                ('gearbox_id', models.IntegerField(choices=[(1, 'Automatic'), (2, 'Ribbed')], null=True)),
                ('is_offroad', models.BooleanField(blank=True, null=True)),
                ('price', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(10000000000000)])),
                ('rent_type_id', models.IntegerField(choices=[(1, 'Hourly'), (2, 'Daily'), (3, 'Weekly'), (4, 'Monthly')], null=True)),
                ('rent', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10000), django.core.validators.MaxValueValidator(1000000000000)])),
                ('built_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1350), django.core.validators.MaxValueValidator(1403)])),
                ('kilometer', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000000)])),
                ('description', models.TextField(blank=True, null=True)),
                ('car_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='office.carmodel')),
            ],
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
