# Generated by Django 5.1.4 on 2024-12-17 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0005_seed_data_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
